---
title: " "
---

<br/><br/>

```{r Organização dos Dados - web, eval=T, echo=F, message=F}

dadoswp7 <- readRDS("pns19IBGE.rds")
  
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "V0001")] <- "UF"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "V0024")] <- "estrato"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "V0015")] <- "tipoentrevista"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "V0026")] <- "sitsensitaria"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "V0031")] <- "tipoarea"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "A018011")] <- "tv"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "A018012")] <- "tvn"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "A018013")] <- "geladeira"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "A018014")] <- "geladeiran"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "A018015")] <- "maqroupa"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "A018016")] <- "maqroupan"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "A018017")] <- "telefone"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "A018018")] <- "telefonen"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "A018019")] <- "celular"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "A018020")] <- "celularn"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "A018021")] <- "microondas"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "A018022")] <- "microondasn"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "A018023")] <- "computador"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "A018024")] <- "computadorn"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "A018025")] <- "motocicleta"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "A018026")] <- "motocicletan"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "A018027")] <- "carro"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "A018028")] <- "carron"
  
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "B001")] <- "CadastroNaUSF"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "B003")] <- "visitasdoac12m"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "B004")] <- "visitaAE"
  
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "C004")] <- "condicaodom"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "C006")] <- "Sexo"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "C008")] <- "idade"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "C00701")] <- "DiaNascimento"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "C00702")] <- "MesNascimento"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "C00703")] <- "AnoNascimento"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "C009")] <- "CorRaca"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "C011")] <- "EstadoCivil"
  
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "I00102")] <- "TemPlanoSaude"
  
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "J001")] <- "EstadoDeSaudeA"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "J00101")] <- "EstadoDeSaudeB"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "J002")] <- "RestricaoPorSaude2s"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "J005")] <- "Acamado2s"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "J007")] <- "DiagCronicas"
  
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "J012")] <- "NumeroConsultas12m"
  
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "J014")] <- "ProcServSaude2s"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "J01502")] <- "ProcServSaude2sMotivo"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "J01602")] <- "ProcServSaude2sOnde"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "J023")] <- "ProcServSaude2sRede"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "J026")] <- "ProcServSaude2sSUS"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "J02702")] <- "ProcServSaude2sQual"
  
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "J05301")] <- "UsouIntegrativa12m"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "J05406")] <- "fezmeditacao12m"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "J05407")] <- "fezyoga12m"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "J05408")] <- "feztaix12m"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "J056")] <- "PagouPeloTratamento"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "J057")] <- "TratamentoPeloSUS"
  
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "P018")] <- "consomeFrutas"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "P050")] <- "fumanopresente"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "P051")] <- "fumounopassado"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "P027")] <- "FreqAlcool1m"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "P034")] <- "exercicio3m"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "P035")] <- "exerciciodias"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "P03701")] <- "exerciciohor"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "P03702")] <- "exerciciomin"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "P04501")] <- "TempoNaTV1d"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "P07004")] <- "FonteInformacaoJornRevis30d"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "P07005")] <- "FonteInformacaoTV30d"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "P07006")] <- "FonteInformacaoRadio30d"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "P07007")] <- "FonteInformacaoInternet30d"
  
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "Q079")] <- "artrite"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "Q074")] <- "asma"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "Q060")] <- "hipercolesterol"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "Q03001")] <- "diabetes"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "Q09010")] <- "DORT"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "Q00201")] <- "hipertensao"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "Q124")] <- "insrencronica"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "Q11604")] <- "doencronpul"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "Q092")] <- "depressao"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "Q11008")] <- "transbip"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "Q11009")] <- "toc"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "Q084")] <- "dor_cron_col"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "Q120")] <- "cancer"
  
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "VDD004A")] <- "niveleducacional"
  colnames(dadoswp7$variables)[which(names(dadoswp7$variables) == "VDF003")] <- "rendafamiliarpc"
  
  dadoswp7$variables <- droplevels(dadoswp7$variables)
  
  #dadoswp7$variables[is.na(dadoswp7$variables$visitasdoac12m),"visitasdoac12m"] <- "Nunca recebeu"
  
  # Criando e modificando variáveis
  library(dplyr)
  library(tidyr)
  
  dadoswp7$variables$exercicio3m = ifelse(dadoswp7$variables$exercicio3m == "Sim",1,0)
  dadoswp7$variables$exerciciodiasB = ifelse(is.na(dadoswp7$variables$exerciciodias),1,dadoswp7$variables$exerciciodias)
  dadoswp7$variables$exerciciodiasC = dadoswp7$variables$exercicio3m + dadoswp7$variables$exerciciodiasB
  dadoswp7$variables$exerciciodiasD = dadoswp7$variables$exerciciodiasC-1
  
dadoswp7$variables$artrite[is.na(dadoswp7$variables$artrite)] = "Não"
dadoswp7$variables$asma[is.na(dadoswp7$variables$asma)] = "Não"
dadoswp7$variables$hipercolesterol[is.na(dadoswp7$variables$hipercolesterol)] = "Não"
dadoswp7$variables$diabetes[is.na(dadoswp7$variables$diabetes)] = "Não"
dadoswp7$variables$DORT[is.na(dadoswp7$variables$DORT)] = "Não"
dadoswp7$variables$hipertensao[is.na(dadoswp7$variables$hipertensao)] = "Não"
dadoswp7$variables$insrencronica[is.na(dadoswp7$variables$insrencronica)] = "Não"
dadoswp7$variables$doencronpul[is.na(dadoswp7$variables$doencronpul)] = "Não"
dadoswp7$variables$depressao[is.na(dadoswp7$variables$depressao)] = "Não"
dadoswp7$variables$dor_cron_col[is.na(dadoswp7$variables$dor_cron_col)] = "Não"
dadoswp7$variables$cancer[is.na(dadoswp7$variables$cancer)] = "Não"

dadoswp7$variables <- dadoswp7$variables %>% mutate (
CorRaca3 = as.factor(ifelse(CorRaca == "Branca","Branca",
                   ifelse(CorRaca =="Preta"|CorRaca=="Parda","Preta ou Marrom","Leste Asiático ou Indígena"))),
EmRelacionamento = as.factor(ifelse(C01001 == "Sim" | C013 == "Sim","Sim","Não")),
Idade = as.factor(ifelse(idade<18, NA,
                         ifelse(idade >= 18 & idade <= 29,"18 a 29",
                                ifelse(idade >= 30 & idade <= 39, "30 a 39",
                                      ifelse(idade >= 40 & idade <= 49,"40 a 49",
                                             ifelse(idade >= 50 & idade <= 64,"50 a 64","Maior que 64")))))),
FezYoga12m = ifelse(fezyoga12m == "Sim",1,0),
  FezYoga12m = replace_na(FezYoga12m, 0),
FezTaix12m = ifelse(feztaix12m == "Sim",1,0),
  FezTaix12m = replace_na(FezTaix12m, 0),
FezMeditacao12m = ifelse(fezmeditacao12m == "Sim",1,0),
  FezMeditacao12m = replace_na(FezMeditacao12m, 0),
FezApenasMeditacao = as.factor(ifelse(fezmeditacao12m=="Sim"&fezyoga12m=="Não"&feztaix12m=="Não","Sim","Não")),
FezApenasYoga = as.factor(ifelse(fezmeditacao12m=="Não"&fezyoga12m=="Sim"&feztaix12m=="Não","Sim","Não")),
FezApenasTaix = as.factor(ifelse(fezmeditacao12m=="Não"&fezyoga12m=="Não"&feztaix12m=="Sim","Sim","Não")),
FezTaixeYoga = as.factor(ifelse(fezmeditacao12m=="Não"&fezyoga12m=="Sim"&feztaix12m=="Sim","Sim","Não")),
FezTaixeMeditacao = as.factor(ifelse(fezmeditacao12m=="Sim"&fezyoga12m=="Não"&feztaix12m=="Sim","Sim","Não")),
FezYogaeMeditacao = as.factor(ifelse(fezmeditacao12m=="Sim"&fezyoga12m=="Sim"&feztaix12m=="Não","Sim","Não")),
FezTaixeMeditacaoeYoga = as.factor(ifelse(fezmeditacao12m=="Sim"&fezyoga12m=="Sim"&feztaix12m=="Sim","Sim","Não")),
QualquerTipoMedit = as.factor(ifelse(FezMeditacao12m==1 | FezYoga12m==1 | FezTaix12m==1,1,0)),
ApenasQualquerTipoMedit = as.factor(ifelse(QualquerTipoMedit==1 & J05402=="Não" & J05403=="Não" & J05404=="Não" &
                                            J05405=="Não"&J05409=="Não"&J054010=="Não","Sim","Não")),
mindbodyx = as.numeric(FezMeditacao12m)+as.numeric(FezYoga12m)+as.numeric(FezTaix12m),
MindBody = as.factor(ifelse(mindbodyx == 0, "Nenhuma",
                         ifelse(mindbodyx == 1, "Uma","Duas ou Três"))),
Regiao = as.factor(ifelse(UF == "Rondônia"|UF == "Acre"|UF == "Amazonas"|UF == "Roraima"|UF == "Pará"|UF == "Amapá"|UF == "Tocantis","Norte",
                          ifelse(UF == "Maranhão"|UF == "Piauí"|UF == "Ceará"|UF == "Rio Grande do Norte"|UF == "Paraíba"|UF == "Pernambuco"|UF == "Alagoas" |UF == "Sergipe"|UF == "Bahia","Nordeste",
                                 ifelse(UF == "Minas Gerais"|UF == "Espírito Santo"|UF == "Rio de Janeiro"|UF == "São Paulo","Sudeste",
                                        ifelse(UF == "Paraná"|UF == "Santa Catarina"|UF == "Rio Grande do Sul","Sul","Centro-Oeste"))))),
Exercicio1s = as.factor(ifelse(exerciciodiasD == 0, "Nenhum dia",
                               ifelse(exerciciodiasD == 1|exerciciodiasD == 2|exerciciodiasD == 3|exerciciodiasD == 4,"De um a quatro dias na semana","Cinco ou mais dias na semana"))),
Tabagismo = as.factor(ifelse(fumanopresente == "Não fumo atualmente", "Não","Sim")),
Artrite = ifelse(artrite == "Sim",1,0),
Asma = ifelse(asma == "Sim",1,0),
Hipercolesterol = ifelse(hipercolesterol == "Sim",1,0),
Diabetes = ifelse(diabetes == "Sim",1,0),
Hipertensao = ifelse(hipertensao == "Sim",1,0),
InsRenCronica = ifelse(insrencronica == "Sim",1,0),
DoenCronPul = ifelse(doencronpul == "Sim",1,0),
Depressao = ifelse(depressao == "Sim",1,0),
TOC = ifelse(toc == "Sim",1,0),
TransBip = ifelse(transbip == "Sim",1,0),
Dor_Cron_Col = ifelse(dor_cron_col == "Sim",1,0),
Cancer = ifelse(cancer == "Sim",1,0),
cronicasx = Artrite+Asma+Hipercolesterol+Diabetes+Hipertensao+InsRenCronica+DoenCronPul,
DoencasCronicas = ifelse(cronicasx == 0, "Nenhuma",
                         ifelse(cronicasx == 1, "Uma",
                                ifelse(cronicasx == 2, "Duas","Três ou mais"))),
TranstornosMentaisx = Depressao+TOC+TransBip,
TranstornosMentais = as.factor(ifelse(TranstornosMentaisx == 0, "Nenhum",
                         ifelse(TranstornosMentaisx == 1, "Um",
                                ifelse(TranstornosMentaisx == 2, "Dois","Três")))),
DoencasCronicas2 = ifelse(DoencasCronicas == "Nenhuma","Não","Sim"),
ConsomeFrutas = as.factor(ifelse(consomeFrutas == 0, "Nunca",
                         ifelse(consomeFrutas == 1| consomeFrutas == 2, "Uma a duas vezes por semana",
                                ifelse(consomeFrutas == 3|consomeFrutas == 4, "Três a quatro vezes por semana","Cinco ou mais vezes por semana")))),
RendaFamiliarPc = as.factor(ntile(rendafamiliarpc, 3)), 
VisitasDoAC12m = as.factor(ifelse(visitasdoac12m == "Nunca recebeu","Nunca recebeu","Já recebeu")),
NivelEducacional = as.factor(ifelse(niveleducacional == "Sem instrução" | niveleducacional == "Fundamental incompleto ou equivalente"|
                                      niveleducacional == "Fundamental completo ou equivalente"| niveleducacional == "Médio incompleto ou equivalente","Menos que nível médio complemento",
                                    ifelse(niveleducacional == "Médio completo ou equivalente", "Médio completo","Superior incompleto ou mais"))),
FezMeditacao12m = as.factor(FezMeditacao12m),
FezYoga12m = as.factor(FezYoga12m),
FezTaix12m = as.factor(FezTaix12m)
)

levels(dadoswp7$variables$RendaFamiliarPc) <- c("0 a 499 reais per capita", "500 a 1087 reais per capita ","1088 reais per capita ou mais")

dadoswp7$variables$Exercicio1s <- factor(dadoswp7$variables$Exercicio1s,
                                              levels = c("Nenhum dia","De um a quatro dias na semana","Cinco ou mais dias na semana"))
dadoswp7$variables$DoencasCronicas <- factor(dadoswp7$variables$DoencasCronicas,
                                              levels = c("Nenhuma", "Uma","Duas","Três ou mais"))
dadoswp7$variables$Regiao <- factor(dadoswp7$variables$Regiao,
                                              levels = c("Norte", "Nordeste","Centro-Oeste","Sudeste","Sul"))
dadoswp7$variables$DORT <- factor(dadoswp7$variables$DORT,
                                              levels = c("Não", "Sim"))
dadoswp7$variables$Tabagismo <- factor(dadoswp7$variables$Tabagismo,
                                              levels = c("Não", "Sim"))
dadoswp7$variables$NivelEducacional <- factor(dadoswp7$variables$NivelEducacional,
                                              levels = c("Menos que nível médio complemento", "Médio completo","Superior incompleto ou mais"))
dadoswp7$variables$CorRaca3 <- factor(dadoswp7$variables$CorRaca3,
                                              levels = c("Branca", "Preta ou Marrom","Leste Asiático ou Indígena"))

dadoswp7$variables$FezApenasMeditacao[is.na(dadoswp7$variables$FezApenasMeditacao)] = "Não"
dadoswp7$variables$FezApenasYoga[is.na(dadoswp7$variables$FezApenasYoga)] = "Não"
dadoswp7$variables$FezApenasTaix[is.na(dadoswp7$variables$FezApenasTaix)] = "Não" 

dadoswp7$variables$Artrite <- as.factor(dadoswp7$variables$Artrite)
levels(dadoswp7$variables$Artrite) <- c("Não","Sim")
dadoswp7$variables$Asma <- as.factor(dadoswp7$variables$Asma)
levels(dadoswp7$variables$Asma) <- c("Não","Sim")
dadoswp7$variables$Hipercolesterol <- as.factor(dadoswp7$variables$Hipercolesterol)
levels(dadoswp7$variables$Hipercolesterol) <- c("Não","Sim")
dadoswp7$variables$Diabetes <- as.factor(dadoswp7$variables$Diabetes)
levels(dadoswp7$variables$Diabetes) <- c("Não","Sim")
dadoswp7$variables$Hipertensao <- as.factor(dadoswp7$variables$Hipertensao)
levels(dadoswp7$variables$Hipertensao) <- c("Não","Sim")
dadoswp7$variables$InsRenCronica  <- as.factor(dadoswp7$variables$InsRenCronica)
levels(dadoswp7$variables$InsRenCronica) <- c("Não","Sim")
dadoswp7$variables$DoenCronPul <- as.factor(dadoswp7$variables$DoenCronPul)
levels(dadoswp7$variables$DoenCronPul) <- c("Não","Sim")
dadoswp7$variables$Depressao <- as.factor(dadoswp7$variables$Depressao)
levels(dadoswp7$variables$Depressao) <- c("Não","Sim")
dadoswp7$variables$TransBip <- as.factor(dadoswp7$variables$TransBip)
levels(dadoswp7$variables$TransBip) <- c("Não","Sim")
dadoswp7$variables$TOC <- as.factor(dadoswp7$variables$TOC)
levels(dadoswp7$variables$TOC) <- c("Não","Sim")
dadoswp7$variables$Dor_Cron_Col <- as.factor(dadoswp7$variables$Dor_Cron_Col)
levels(dadoswp7$variables$Dor_Cron_Col) <- c("Não","Sim")
dadoswp7$variables$Cancer <- as.factor(dadoswp7$variables$Cancer)
levels(dadoswp7$variables$Cancer) <- c("Não","Sim")

dadoswp7$variables <- dadoswp7$variables %>% 
  select(FezMeditacao12m,FezYoga12m,FezTaix12m,QualquerTipoMedit,
         FezApenasMeditacao,FezApenasYoga,FezApenasTaix,
         MindBody,
         Sexo,Idade,CorRaca3,EmRelacionamento,Regiao,NivelEducacional,RendaFamiliarPc,
         TemPlanoSaude,
         DoencasCronicas,DoencasCronicas2,Artrite,Asma,Hipercolesterol,Diabetes,Hipertensao,InsRenCronica,DoenCronPul,
         Cancer,Dor_Cron_Col,DORT,
         Depressao,
         Tabagismo,FreqAlcool1m,Exercicio1s,
         UPA_PNS, estrato, M001)

dadoswp7$variables$TemPlanoSaude <- relevel(dadoswp7$variables$TemPlanoSaude, ref = "Não")
dadoswp7$variables$Tabagismo <- relevel(dadoswp7$variables$Tabagismo, ref = "Não")
dadoswp7$variables$Exercicio1s <- relevel(dadoswp7$variables$Exercicio1s, ref = "Nenhum dia")
dadoswp7$variables$CorRaca3 <- relevel(dadoswp7$variables$CorRaca3, ref = "Preta ou Marrom")
dadoswp7$variables$EmRelacionamento <- relevel(dadoswp7$variables$EmRelacionamento, ref = "Sim")

saveRDS(dadoswp7,"dadoswp7a.rds")

dadosibge <-dadoswp7$variables

dadosibge <- dadosibge %>% filter(M001 == "Realizada")
dadosibge <- dadosibge %>% filter(!is.na(Idade))
dadosibge <- dadosibge %>% filter(!is.na(RendaFamiliarPc))

saveRDS(dadosibge,"dadosibge.rds")

```

```{r LCA, eval=F, message=F, warning=F}

# Análise de classes latentes

library(poLCA)
f <- cbind(FezMeditacao12m,FezYoga12m,FezTaix12m)~1

lca1 <- poLCA(f,dadospnsx,nclass=7, graphs = T)

# run a sequence of models with 1-10 classes and print out the model with the lowest BIC
max_II <- -100000
min_bic <- 100000
for(i in 2:10){
  lc <- poLCA(f, dadospnsx, nclass=i, maxiter=3000, 
              tol=1e-5, na.rm=FALSE,  
              nrep=10, verbose=TRUE, calc.se=TRUE)
  if(lc$bic < min_bic){
    min_bic <- lc$bic
    LCA_best_model<-lc
  }
}    	
LCA_best_model


# Construção da tabela com os critérios

## models with different number of groups without covariates:
set.seed(01012)
lc1<-poLCA(f, data=dadossps, nclass=1, na.rm = FALSE, nrep=30, maxiter=3000) #Loglinear independence model.
lc2<-poLCA(f, data=dadossps, nclass=2, na.rm = FALSE, nrep=30, maxiter=3000)
lc3<-poLCA(f, data=dadossps, nclass=3, na.rm = FALSE, nrep=30, maxiter=3000)
lc4<-poLCA(f, data=dadossps, nclass=4, na.rm = FALSE, nrep=30, maxiter=3000) 
lc5<-poLCA(f, data=dadossps, nclass=5, na.rm = FALSE, nrep=30, maxiter=3000)
lc6<-poLCA(f, data=dadossps, nclass=6, na.rm = FALSE, nrep=30, maxiter=3000)
lc7<-poLCA(f, data=dadossps, nclass=7, na.rm = FALSE, nrep=30, maxiter=3000)
lc8<-poLCA(f, data=dadossps, nclass=8, na.rm = FALSE, nrep=30, maxiter=3000)
lc9<-poLCA(f, data=dadossps, nclass=9, na.rm = FALSE, nrep=30, maxiter=3000)

# generate dataframe with fit-values

results <- data.frame(Modell=c("Modell 1"),
                      log_likelihood=lc1$llik,
                      df = lc1$resid.df,
                      BIC=lc1$bic,
                      ABIC=  (-2*lc1$llik) + ((log((lc1$N + 2)/24)) * lc1$npar),
                      CAIC = (-2*lc1$llik) + lc1$npar * (1 + log(lc1$N)), 
                      likelihood_ratio=lc1$Gsq)
results$Modell<-as.integer(results$Modell)
results[1,1]<-c("Modell 1")
results[2,1]<-c("Modell 2")
results[3,1]<-c("Modell 3")
results[4,1]<-c("Modell 4")
results[5,1]<-c("Modell 5")
results[6,1]<-c("Modell 6")
results[7,1]<-c("Modell 7")
results[8,1]<-c("Modell 8")
results[9,1]<-c("Modell 9")

results[2,2]<-lc2$llik
results[3,2]<-lc3$llik
results[4,2]<-lc4$llik
results[5,2]<-lc5$llik
results[6,2]<-lc6$llik
results[7,2]<-lc7$llik
results[8,2]<-lc8$llik
results[9,2]<-lc9$llik

results[2,3]<-lc2$resid.df
results[3,3]<-lc3$resid.df
results[4,3]<-lc4$resid.df
results[5,3]<-lc5$resid.df
results[6,3]<-lc6$resid.df
results[7,3]<-lc7$resid.df
results[8,3]<-lc8$resid.df
results[9,3]<-lc9$resid.df

results[2,4]<-lc2$bic
results[3,4]<-lc3$bic
results[4,4]<-lc4$bic
results[5,4]<-lc5$bic
results[6,4]<-lc6$bic
results[7,4]<-lc7$bic
results[8,4]<-lc8$bic
results[9,4]<-lc9$bic

results[2,5]<-(-2*lc2$llik) + ((log((lc2$N + 2)/24)) * lc2$npar) #abic
results[3,5]<-(-2*lc3$llik) + ((log((lc3$N + 2)/24)) * lc3$npar)
results[4,5]<-(-2*lc4$llik) + ((log((lc4$N + 2)/24)) * lc4$npar)
results[5,5]<-(-2*lc5$llik) + ((log((lc5$N + 2)/24)) * lc5$npar)
results[6,5]<-(-2*lc6$llik) + ((log((lc6$N + 2)/24)) * lc6$npar)
results[7,5]<-(-2*lc8$llik) + ((log((lc7$N + 2)/24)) * lc7$npar)
results[8,5]<-(-2*lc9$llik) + ((log((lc8$N + 2)/24)) * lc8$npar)
results[9,5]<-(-2*lc9$llik) + ((log((lc9$N + 2)/24)) * lc9$npar)


results[2,6]<- (-2*lc2$llik) + lc2$npar * (1 + log(lc2$N)) #caic
results[3,6]<- (-2*lc3$llik) + lc3$npar * (1 + log(lc3$N))
results[4,6]<- (-2*lc4$llik) + lc4$npar * (1 + log(lc4$N))
results[5,6]<- (-2*lc5$llik) + lc5$npar * (1 + log(lc5$N))
results[6,6]<- (-2*lc6$llik) + lc6$npar * (1 + log(lc6$N))
results[7,6]<- (-2*lc7$llik) + lc7$npar * (1 + log(lc7$N))
results[8,6]<- (-2*lc8$llik) + lc8$npar * (1 + log(lc8$N))
results[9,6]<- (-2*lc9$llik) + lc9$npar * (1 + log(lc9$N))

results[2,7]<-lc2$Gsq
results[3,7]<-lc3$Gsq
results[4,7]<-lc4$Gsq
results[5,7]<-lc5$Gsq
results[6,7]<-lc6$Gsq
results[7,7]<-lc7$Gsq
results[8,7]<-lc8$Gsq
results[9,7]<-lc9$Gsq

```


### Características da amostra

<br/>

```{r Características da amostra, eval=T, echo=FALSE, message=F, warning=F}

dadoswp7a <- readRDS("dadoswp7a.rds")

library(gtsummary)
tbl_svysummary(dadoswp7a, include=c(FezMeditacao12m,FezYoga12m,FezTaix12m,QualquerTipoMedit,
               Sexo,Idade,CorRaca3,EmRelacionamento,Regiao,NivelEducacional,RendaFamiliarPc,
                         TemPlanoSaude,
                         DoencasCronicas,Artrite,Asma,Hipercolesterol,Diabetes,Hipertensao,InsRenCronica,DoenCronPul,
                         Dor_Cron_Col,DORT,
                         Depressao,
                         Tabagismo,FreqAlcool1m,Exercicio1s),
               digits = list(all_categorical() ~ c(2)),
               missing = 'no')



#Retirados: ProcServSaude2sMotivo,ProcServSaude2sOnde,,ProcServSaude2sQua

```

<br/><br/>

### Características dos que utilizaram práticas mente-corpo: total  

<br/>  

```{r Caracteristicas - geral, eval=T, echo=FALSE, message=F, warning=F}

tbl_svysummary(dadoswp7a,by = QualquerTipoMedit, 
               include=c(Sexo,Idade,CorRaca3,EmRelacionamento,Regiao,NivelEducacional,RendaFamiliarPc,
                         TemPlanoSaude,
                         DoencasCronicas,Artrite,Asma,Hipercolesterol,Diabetes,Hipertensao,InsRenCronica,DoenCronPul,
                         Dor_Cron_Col,DORT,
                         Depressao,
                         Tabagismo,FreqAlcool1m,Exercicio1s),
               digits = list(all_categorical() ~ c(2)),
               missing = 'no')

#tbl %>%
#  modify_table_header(
#    column = stat_1,
#    hide = TRUE
#  )

#print(tbl)

```

<br/><br/>

### Características dos que utilizaram práticas mente-corpo: meditação

<br/>  

```{r Características - meditação, eval=T, echo=FALSE, message=F, warning=F}

tbl_svysummary(dadoswp7a,by = FezMeditacao12m, 
               include=c(Sexo,Idade,CorRaca3,EmRelacionamento,Regiao,NivelEducacional,RendaFamiliarPc,
                         TemPlanoSaude,
                         DoencasCronicas,Artrite,Asma,Hipercolesterol,Diabetes,Hipertensao,InsRenCronica,DoenCronPul,
                         Dor_Cron_Col,DORT,
                         Depressao,
                         Tabagismo,FreqAlcool1m,Exercicio1s),
               digits = list(all_categorical() ~ c(2)),
               missing = 'no')

#tbl %>%
#  modify_table_header(
#    column = stat_1,
#    hide = TRUE
#  )

#print(tbl)

```

<br/><br/>

### Características dos que utilizaram práticas mente-corpo: yoga

<br/>  

```{r Características yoga, eval=T, echo=FALSE, message=F, warning=F}

tbl_svysummary(dadoswp7a,by = FezYoga12m, 
               include=c(Sexo,Idade,CorRaca3,EmRelacionamento,Regiao,NivelEducacional,RendaFamiliarPc,
                         TemPlanoSaude,
                         DoencasCronicas,Artrite,Asma,Hipercolesterol,Diabetes,Hipertensao,InsRenCronica,DoenCronPul,
                         Dor_Cron_Col,DORT,
                         Depressao,
                         Tabagismo,FreqAlcool1m,Exercicio1s),
               digits = list(all_categorical() ~ c(2)),
               missing = 'no')

#tbl %>%
#  modify_table_header(
#    column = stat_1,
#    hide = TRUE
#  )

#print(tbl)

```

<br/><br/>

### Características dos que utilizaram práticas mente-corpo: Tai chi/ lian gong/ qigong

<br/>  

```{r Características - taix, eval=T, echo=FALSE, message=F, warning=F}

tbl_svysummary(dadoswp7a,by = FezTaix12m, 
               include=c(Sexo,Idade,CorRaca3,EmRelacionamento,Regiao,NivelEducacional,RendaFamiliarPc,
                         TemPlanoSaude,
                         DoencasCronicas,Artrite,Asma,Hipercolesterol,Diabetes,Hipertensao,InsRenCronica,DoenCronPul,
                         Dor_Cron_Col,DORT,
                         Depressao,
                         Tabagismo,FreqAlcool1m,Exercicio1s),
               digits = list(all_categorical() ~ c(2)),
               missing = 'no')

#tbl %>%
#  modify_table_header(
#    column = stat_1,
#    hide = TRUE
#  )

#print(tbl)

```

```{r Prevalências totais, eval=F, echo=FALSE, message=F, warning=F}

dadoswp7a <- readRDS("dadoswp7a.rds")

library(survey)

svymean(~FezMeditacao12m, design=dadoswp7a, na.rm=TRUE)


```

```{r Características - tabela final, eval=F, echo=FALSE, message=F, warning=F}

dadoswp7a <- readRDS("dadoswp7a.rds")

library(survey)

# Tabela 1

svyby(~Idade, ~FezMeditacao12m, dadoswp7a, na = TRUE, svymean)

svyby(~RendaFamiliarPc, ~FezMeditacao12m, dadoswp7a, na = TRUE, svymean)

# Tabela 2

svyby(~FezMeditacao12m, ~Dor_Cron_Col, dadoswp7a, na = TRUE, svymean)

svyby(~FezMeditacao12m, ~FezYoga12m, dadoswp7a, na = TRUE, svymean)



#dadoswp7$variables[is.na(dadoswp7$variables$Idade),] <- "Menor de 18"

#svyby(~I(Idade),~FezMeditacao12m,design=subset(dados, !is.na(Idade)), svymean,vartype="se", method="me")

#dadoswp7$variables[is.na(dadoswp7$variables$visitasdoac12m),"visitasdoac12m"] <- "Nunca recebeu"

#svyby(~I(Regiao),~FezMeditacao12m,design=dadoswp7, svymean,vartype="se",method="me",df=degf(dadoswp7))

#svyby(~I(Regiao),~FezMeditacao12m,design=subset(dadoswp7, !is.na(Exercicio1s)), svymean,vartype="se",method="me")
      
#svyby(~I(RendaFamiliarPc),~FezMeditacao12m,design=dadoswp7, svymean,vartype="se",method="me",na.rm.all = TRUE)
#svyby(~I(Idade),~FezMeditacao12m,design=dadoswp7, svymean,vartype="se",method="me",na.rm.by = TRUE)

#svyby(~I(RendaFamiliarPc),~FezMeditacao12m,design=subset(dadoswp7, !is.na(Exercicio1s)), svymean,vartype="se",method="me")

#design=subset(dadosPNS, C006=="Mulher")
#dadoswp7$variables <- dadoswp7$variables  %>% filter(is.na(dadoswp7$variables$RendaFamiliarPc))

#svyby(~I(RendaFamiliarPc),~FezMeditacao12m,design=dadoswp7, svymean,vartype="se",method="me",
#      df=degf(dadoswp7))


```
